### ISSUE TITLE
Change font size

### ISSUE THREAD

**Issue by RangerMauve** [gruehle/dev-docs-viewer#3]
Hey, it'd be nice if we could apply custom CSS, or have a way to just change the zoom level on the frame. I sadly don't have a full-sized display most of the time and the default sizes for everything is a bit too large for comfort.

**Comment by RangerMauve** [comment]
Right now I've been manually setting the size using this code:

``` javascript
docuement
  .getElementById("devdocs-viewer-iframe")
  .contentDocument.head.innerHTML+=
    "<style>* {font-size:10px !important;}</style>";
```

I've just been entering it into the dev tools, but it'd be awesome if you could maybe provide a way to add styles from within the plugin.

**Comment by gruehle** [comment]
@RangerMauve thanks for the feedback! 

I'm intentionally keeping the design minimal for this extension, and don't want to take up any more space with adding preferences/settings.

Here are a couple options so you can avoid having to hack in dev tools every time you start Brackets:
- Contact @DevDocs on twitter and ask for a font size preference to be added to the devdocs.io site (this extension simply loads the site in an iframe)
- Write a Brackets extension that does your hack. You could add a new menu item that forces the devdocs font size to 10px.
- Fork this extension and inject the size when the panel is created.
